server:
  port: 8080

spring:
  application:
    name: academic-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/academic_db}
    username: ${SPRING_DATASOURCE_USERNAME:campus}
    password: ${SPRING_DATASOURCE_PASSWORD:campus123}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:campus}
    password: ${SPRING_RABBITMQ_PASSWORD:campus123}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

# Configuracion propia del ecosistema
campus:
  messaging:
    exchange: campus.events
    routing-keys:
      student-enrolled: student.enrolled
      student-status-updated: student.status.updated
